### ISSUE TITLE
PHP 7.2: Declaration of ParallelDownloader::getRemoteContents should be compatible with RemoteFileSystem::getRemoteContents

### ISSUE THREAD

**Issue by abelardolg** [groovili/socket-chat#3]
Hi,
By using PHP7.2 under Ubuntu 18.04, I run into the app directory:
`composer install`
and it gave me this error:
```
[ErrorException]                                                                                                                                  
  Declaration of Symfony\Flex\ParallelDownloader::getRemoteContents($originUrl, $fileUrl, $context) should be compatible with Composer\Util\Remote  
  Filesystem::getRemoteContents($originUrl, $fileUrl, $context, ?array &$responseHeaders = NULL) 
```   
I previously downloade your code via .zip.

What's wrong?

Cheers.

**Comment by groovili** [comment]
@abelardolg strange, just installed recent updates via composer and successfully launched app.
What are your exact PHP and Composer versions (PHP7.2.?)?
The first thing you should try - run composer self-update and update PHP to the latest version.
